<?php

use PHPUnit\Framework\TestCase;

class AdminTest extends TestCase
{
    private function makeAdmin(): Admin
    {
        return new Admin(
            name:     'Sam Admin',
            email:    'admin@gymfit.fr',
            password: 'hashed-password'
        );
    }

    public function testConstructorAssignsRequiredFields(): void
    {
        $admin = $this->makeAdmin();

        $this->assertSame('Sam Admin', $admin->getName());
        $this->assertSame('admin@gymfit.fr', $admin->getEmail());
        $this->assertSame('hashed-password', $admin->getPassword());
    }

    public function testDefaultRoleIsAdmin(): void
    {
        $this->assertSame('admin', $this->makeAdmin()->getRole());
    }

    public function testCreatedAtIsAutoGeneratedWhenNotProvided(): void
    {
        $admin = $this->makeAdmin();

        $this->assertNotNull($admin->getCreatedAt());
        $this->assertMatchesRegularExpression(
            '/^\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2}$/',
            $admin->getCreatedAt()
        );
    }

    public function testCreatedAtIsKeptWhenProvided(): void
    {
        $admin = new Admin(
            name:      'Sam Admin',
            email:     'admin@gymfit.fr',
            password:  'hashed-password',
            createdAt: '2025-12-01 08:00:00'
        );

        $this->assertSame('2025-12-01 08:00:00', $admin->getCreatedAt());
    }

    public function testSettersUpdateValues(): void
    {
        $admin = $this->makeAdmin();

        $admin->setId(1);
        $admin->setName('Nouveau Nom');
        $admin->setEmail('nouveau@gymfit.fr');
        $admin->setPassword('new-hash');
        $admin->setRole('superadmin');

        $this->assertSame(1, $admin->getId());
        $this->assertSame('Nouveau Nom', $admin->getName());
        $this->assertSame('nouveau@gymfit.fr', $admin->getEmail());
        $this->assertSame('new-hash', $admin->getPassword());
        $this->assertSame('superadmin', $admin->getRole());
    }
}
