<?php

use PHPUnit\Framework\TestCase;

class MemberTest extends TestCase
{
    private function makeMember(): Member
    {
        return new Member(
            firstName: 'Jean',
            lastName:  'Dupont',
            email:     'jean.dupont@example.com',
            password:  'hashed-password',
            phone:     '0612345678'
        );
    }

    public function testConstructorAssignsRequiredFields(): void
    {
        $member = $this->makeMember();

        $this->assertSame('Jean', $member->getFirstName());
        $this->assertSame('Dupont', $member->getLastName());
        $this->assertSame('jean.dupont@example.com', $member->getEmail());
        $this->assertSame('hashed-password', $member->getPassword());
        $this->assertSame('0612345678', $member->getPhone());
    }

    public function testDefaultStatusIsPending(): void
    {
        $this->assertSame('pending', $this->makeMember()->getStatus());
    }

    public function testDefaultOptionalFieldsAreNull(): void
    {
        $member = $this->makeMember();

        $this->assertNull($member->getId());
        $this->assertNull($member->getIdSubscription());
        $this->assertNull($member->getAvatar());
    }

    public function testRegistrationDateIsAutoGeneratedWhenNotProvided(): void
    {
        $member = $this->makeMember();

        $this->assertNotNull($member->getRegistrationDate());
        $this->assertMatchesRegularExpression(
            '/^\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2}$/',
            $member->getRegistrationDate()
        );
    }

    public function testRegistrationDateIsKeptWhenProvided(): void
    {
        $member = new Member(
            firstName:        'Jean',
            lastName:         'Dupont',
            email:            'jean.dupont@example.com',
            password:         'hashed-password',
            phone:            '0612345678',
            registrationDate: '2026-01-15 10:30:00'
        );

        $this->assertSame('2026-01-15 10:30:00', $member->getRegistrationDate());
    }

    public function testSettersUpdateValues(): void
    {
        $member = $this->makeMember();

        $member->setId(42);
        $member->setFirstName('Marie');
        $member->setLastName('Curie');
        $member->setEmail('marie.curie@example.com');
        $member->setPassword('new-hash');
        $member->setPhone('0698765432');
        $member->setStatus('active');
        $member->setIdSubscription(3);
        $member->setAvatar('avatar.png');

        $this->assertSame(42, $member->getId());
        $this->assertSame('Marie', $member->getFirstName());
        $this->assertSame('Curie', $member->getLastName());
        $this->assertSame('marie.curie@example.com', $member->getEmail());
        $this->assertSame('new-hash', $member->getPassword());
        $this->assertSame('0698765432', $member->getPhone());
        $this->assertSame('active', $member->getStatus());
        $this->assertSame(3, $member->getIdSubscription());
        $this->assertSame('avatar.png', $member->getAvatar());
    }

    public function testIdSubscriptionCanBeResetToNull(): void
    {
        $member = $this->makeMember();
        $member->setIdSubscription(3);
        $member->setIdSubscription(null);

        $this->assertNull($member->getIdSubscription());
    }
}
